"""Reports derived exclusively from aggregate metrics."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "No observations."
    keys = list(rows[0])

    def display(value: Any) -> str:
        if isinstance(value, float):
            return f"{value:.6f}"
        return str(value).replace("|", "\\|")

    return "\n".join(
        [
            "| " + " | ".join(keys) + " |",
            "|" + "---|" * len(keys),
            *["| " + " | ".join(display(row[key]) for key in keys) + " |" for row in rows],
        ]
    )


def generate_reports(profile: dict[str, Any], docs: Path) -> None:
    docs.mkdir(parents=True, exist_ok=True)
    provenance = f"Dataset `{profile['dataset_version']}`. BANK_CLOCK `{profile['bank_clock']}`. Generated by the local pipeline; all values below are aggregates."
    temporal = profile.get("temporal_automation")
    temporal_table = "See the [operational temporal guard](data-temporal-guard.md)."
    if temporal:
        if temporal.get("version") == 2:
            temporal_table = (
                _table(
                    [
                        {
                            key: temporal[key]
                            for key in (
                                "window_rows",
                                "flagged_transaction_rows",
                                "unflagged_transaction_rows",
                                "window_business_date_mismatch_warning",
                            )
                        }
                    ]
                )
                + "\n\n"
                + _table(
                    [
                        {
                            "reason": reason,
                            "overlapping_findings": count,
                            "primary_reason_rows": temporal["primary_reason_counts"][reason],
                        }
                        for reason, count in temporal["findings"].items()
                    ]
                )
            )
        else:
            temporal_table = _table([temporal])
    dq = [
        "# Data quality report",
        "",
        provenance,
        "",
        "## Gate and exclusions",
        "",
        "Every check records its owner, threshold and scope. Snapshot-scoped FAIL checks block promotion. `OWNER-complaints-affected-product` is a field-scoped FAIL: the unsafe link and all complaint text are excluded from every gold/serving model. Complaint counts join only the complaint customer ID to customers. This is an explicit projection restriction, not permission to follow the link.",
        "",
        _table(profile["checks"]),
        "",
        "## Source volumes",
        "",
        _table([{"table": key, **value} for key, value in profile["tables"].items()]),
        "",
        "## Per-column null rates",
        "",
        "SQL NULL counts after contract conversion; `null_rate` is nulls/rows (0–1). Nullable does not mean defective: many fields are conditional. Blank non-null strings are counted separately. Provenance columns are excluded. Cast failures remain invalid-row failures, not missing-value imputation.",
        "",
        _table(profile.get("column_null_rates", [])),
        "",
        "## Duplicate reconciliation",
        "",
        "Exact records include their source primary key. Payload fingerprints omit the ID and partition date to detect replay with regenerated IDs. Business/event fingerprints are candidate collisions, not proof of duplicate activity; no records are collapsed. Counts report excess rows beyond the first member of each group. Unique PKs logically imply zero exact full-row duplicates.",
        "",
        "See [delivery reconciliation](data-quality-reconciliation.md) for the direct-source scan, full 13-table scope, fingerprint keys, null denominators, additional relationships and volume explanations.",
        "",
        "## Definitions",
        "",
        "- Silver checks every row against contract types, nullability, enums and ranges. Invalid rows are quarantined; primary keys and foreign keys are checked over the complete snapshot.",
        "- Windows are half-open UTC intervals `[BANK_CLOCK - N days, BANK_CLOCK)`. The bank business date is timestamp minus six hours, converted to date.",
        "- Candidate counts include every customer, including zero-transaction customers. Quantiles use continuous interpolation.",
        "- Future dimension updates compare their UTC timestamp to BANK_CLOCK. The initial report compared calendar dates to the last source business date; these definitions differ.",
        "- All source checksums are compared on every run, including the last seven business days and older partitions. Unchanged source transformations are reused. Full gold models rebuild when a source, contract, transformation or clock changes.",
        "- Silver Parquet objects retain source provenance. Snapshot views add the active `_dataset_version`; gold persists it on each row. Aggregate lineage uses the snapshot manifest hash and an aggregate source label.",
        "",
        "## Known anomalies",
        "",
        "### Temporal automation boundary",
        "",
        temporal_table,
        "",
        "Temporal anomalies warn and remain visible. Serving transactions gain a nullable temporal_quality_reason; the lead-owned policy must hand off flagged disputes. Business-date mismatches remain warnings. The loader verifies complete exported row sets, authority fields and flags before any bank connection. Activation requires the policy image, nullable TEXT column and serving reload together; these post-v4 changes do not alter official evaluation numbers.",
        "",
        "### Complaint ownership",
        "",
        _table([profile["complaint_ownership"]]),
        "",
        "### FX recomputation",
        "",
        _table([profile["fx"]]),
        "",
        "### Text degeneracy",
        "",
        _table(
            [
                {"source": key, "metrics": json.dumps(value, sort_keys=True)}
                for key, value in profile["text_degeneracy"].items()
            ]
        ),
        "",
        "Reproduce with `uv run --extra data-ml python -m aclara.data.cli build`. Source rows and detailed diagnostics remain in the ignored lake.",
        "",
    ]
    (docs / "data-quality-report.md").write_text("\n".join(dq))
    report = [
        "# Problem analysis v1",
        "",
        provenance,
        "",
        "Historical operations are context on a synthetic workload, not the evaluation baseline or evidence of a production improvement.",
        "",
        "## Demand and outcomes",
        "",
        _table(profile["contact_reasons"]),
        "",
        "First-contact resolution averages non-null `was_resolved`; the denominator is shown. Handle-time share uses observed duration, without imputing null durations. Unrecognized-charge intake combines frequent transaction questions with low-resolution complaints; fee disputes remain a human workflow.",
        "",
        "### Complaint mix",
        "",
        _table(profile["complaint_mix"]),
        "",
        "Resolution days are the supplied calendar-day field, averaged only over non-null rows. Counts include all delivered historical records.",
        "",
        "### Channels",
        "",
        _table(profile["contact_channels"]),
        "",
        _table(profile["complaint_channels"]),
        "",
        "### Weekday demand",
        "",
        _table(profile["day_of_week"]),
        "",
        "Weekday rates divide by the number of distinct observed UTC dates for each weekday, accounting for unequal calendar coverage. Hour-of-day aggregates are available in the machine-readable report; UTC does not represent each customer's local hour.",
        "",
        "## Hypotheses",
        "",
        "### CSAT and resolution",
        "",
        _table(profile["csat_by_resolution"]),
        "",
        "Only CSAT surveys linked by interaction and customer are used. The score supports differ by resolution, consistent with synthetic generation. CSAT provides no independent causal evidence that resolving a contact improves satisfaction.",
        "",
        "### Accent routing",
        "",
    ]
    for name, values in profile["accent_test"].items():
        report += [f"Accent comparison: {name}.", "", _table(values), ""]
    report += [
        "Unknown accents are excluded. Small observed differences do not justify accent-based routing; these are descriptive comparisons without random assignment, and a null difference is not proof of equivalence.",
        "",
        "### Fraud score",
        "",
        _table(profile["fraud_thresholds"]),
        "",
        "Compare flagged/total and window_flagged/window_n at thresholds 27 and 30. The discontinuity is consistent with generator leakage. `is_fraud` is an analytical label only, excluded from all gold/serving fields and matcher features. No fraud model is trained.",
        "",
        "### App errors preceding contact",
        "",
        _table(profile["app_error_contact"]),
        "",
        "Method: Android/iOS events for transaction viewing, transfer initiation or payment initiation, split into Error and other event types. Link to the next contact by the same customer within 48 hours; exclude events in the final 48 hours before BANK_CLOCK. This event-level comparison may include repeated events per customer and is confounded by activity; it is not causal and does not supply independent customer-level significance.",
        "",
        "## Operational constraints",
        "",
        _table([profile["agents"]]),
        "",
        "PT fraud routing needs explicit language and specialty fallback. Recorded staffing attributes are not evidence of agents' live availability.",
        "",
        "### Ledger candidate sets",
        "",
        _table([profile["candidate_counts"]]),
        "",
        _table([profile["pending_window"]]),
        "",
        "The brief's reference figures (494,755 transactions; candidate median 3, p90 8, maximum 28; 26,475 customers without candidates; 9,963 pending and 8,741 older than 14 days) are not forced to match. This report uses exact timestamp windows and all customers, including zeros. Pipeline values above are authoritative.",
        "",
        "### Currency and country",
        "",
        _table(profile["currency_counts"]),
        "",
        f"Foreign-country transactions after ISO normalization: {profile['foreign_transactions']:,}. FX uses the latest rate on or before each business date; nearest-prior fallbacks are flagged. Source USD amounts are retained separately from recomputed values.",
        "",
        _table([profile["fx"]]),
        "",
        "## What this data supports",
        "",
        "| Supports | Does not establish |",
        "|---|---|",
        "| Scoped ledger lookup and status explanations | Settlement, expiry or reversal timing |",
        "| Date-specific FX and skill/language routing | Reliable channel/type semantics or live staffing |",
        "| Contact/complaint demand and DQ evidence | Causal CSAT or app-error effects |",
        "| Synthetic charge-recollection experiments | Real customer recollections or Portuguese language performance |",
        "| Customer-level complaint counts | Complaint-to-product/transaction links |",
        "",
        "Intended customer outcomes: grounded answers, accurate intake and truthful action reporting. Intended business outcomes: first-contact resolution on charge questions, reduced agent time, bounded SLA risk and no unauthorized disclosure. These are targets to evaluate against B1, not measured benefits from this analysis.",
        "",
        "## Reproduction",
        "",
        "Run the data build, then `uv run --extra data-ml python analysis/problem_analysis.py`. The script reads the active gold aggregate mart and regenerates this document. Figures use aggregate data only.",
        "",
    ]
    (docs / "problem-analysis.md").write_text("\n".join(report))
    (docs / "data").mkdir(exist_ok=True)
    (docs / "data/problem-analysis-aggregates.json").write_text(
        json.dumps(profile, indent=2, sort_keys=True, default=str) + "\n"
    )
