"""Render the policy catalog from the versioned runtime rule registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from aclara.policy.rules import catalog


def render() -> str:
    version, rules = catalog()
    lines = [
        "# Policy catalog",
        "",
        f"Policy version: **{version}**. Generated by `python -m scripts.generate_policy_catalog` from the runtime registry and `config/policy.yaml`.",
        "",
        "Includes brief §9 IDs and post-v4 data-quality controls. **Status is implementation coverage, not a safety certification.** Each row links its implementation tests; this is synthetic-policy coverage, not real-bank validation. ES/PT descriptions are model-authored and await the agreed language review. All policies are synthetic demo rules.",
        "",
        "| ID | ES | PT | EN | Parameters | Coverage | Enforcement | Tests |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for rule in rules:
        lines.append(
            "| "
            + " | ".join(
                [
                    rule.id,
                    rule.es,
                    rule.pt,
                    rule.en,
                    json.dumps(rule.parameters, ensure_ascii=False),
                    rule.status,
                    "<br>".join(rule.enforcement) or "—",
                    "<br>".join(rule.tests) or "No implementation tests yet",
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path("docs/policy-catalog.md")
    expected = render()
    if args.check:
        if not path.exists() or path.read_text() != expected:
            raise SystemExit("Policy catalog is stale")
    else:
        path.write_text(expected)


if __name__ == "__main__":
    main()
